// Code generated by "stringer -type=Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Identifier-1]
	_ = x[IntegerLiteral-2]
	_ = x[StringLiteral-3]
	_ = x[FloatLiteral-4]
	_ = x[CharacterLiteral-5]
	_ = x[KwFn-6]
	_ = x[KwDo-7]
	_ = x[KwVar-8]
	_ = x[KwMut-9]
	_ = x[KwReturn-10]
	_ = x[KwEnd-11]
	_ = x[KwChar-12]
	_ = x[KwInt-13]
	_ = x[KwBool-14]
	_ = x[KwNull-15]
	_ = x[KwUnit-16]
	_ = x[KwString-17]
	_ = x[KwFloat-18]
	_ = x[KwIf-19]
	_ = x[KwThen-20]
	_ = x[KwElse-21]
	_ = x[KwStruct-22]
	_ = x[KwIs-23]
	_ = x[KwImportC-24]
	_ = x[KwImport-25]
	_ = x[KwLoop-26]
	_ = x[KwStop-27]
	_ = x[KwDefer-28]
	_ = x[KwEnum-29]
	_ = x[Plus-30]
	_ = x[Minus-31]
	_ = x[Star-32]
	_ = x[Slash-33]
	_ = x[Equal-34]
	_ = x[EqualEqual-35]
	_ = x[Bang-36]
	_ = x[BangEqual-37]
	_ = x[Less-38]
	_ = x[LessEqual-39]
	_ = x[Greater-40]
	_ = x[GreaterEqual-41]
	_ = x[Arrow-42]
	_ = x[Modulo-43]
	_ = x[Pipe-44]
	_ = x[LogicalOr-45]
	_ = x[LogicalAnd-46]
	_ = x[Ampersand-47]
	_ = x[Caret-48]
	_ = x[Tilde-49]
	_ = x[PlusEqual-50]
	_ = x[MinusEqual-51]
	_ = x[StarEqual-52]
	_ = x[SlashEqual-53]
	_ = x[ModuloEqual-54]
	_ = x[CaretEqual-55]
	_ = x[PipeEqual-56]
	_ = x[AmpersandEqual-57]
	_ = x[PlusPlus-58]
	_ = x[MinusMinus-59]
	_ = x[LessLess-60]
	_ = x[GreaterGreater-61]
	_ = x[LeftParen-62]
	_ = x[RightParen-63]
	_ = x[LeftBrace-64]
	_ = x[RightBrace-65]
	_ = x[Comma-66]
	_ = x[Semicolon-67]
	_ = x[Colon-68]
	_ = x[Dot-69]
	_ = x[LeftBracket-70]
	_ = x[RightBracket-71]
	_ = x[Newline-72]
	_ = x[EOF-73]
	_ = x[Error-74]
}

const _Kind_name = "unknownidentifierinteger_literalstring_literalfloat_literalcharacter_literalkw_fnkw_dokw_varkw_mutkw_returnkw_endkw_charkw_intkw_boolkw_nullkw_unitkw_stringkw_floatkw_ifkw_thenkw_elsekw_structkw_iskw_importckw_importkw_loopkw_stopkw_deferkw_enumplusminusstarslashequalequal_equalbangbang_equallessless_equalgreatergreater_equalarrowmodulopipelogical_orlogical_andampersandcarettildeplus_equalminus_equalstar_equalslash_equalmodulo_equalcaret_equalpipe_equalampersand_equalplus_plusminus_minusless_lessgreater_greaterleft_parenright_parenleft_braceright_bracecommasemicoloncolondotleft_bracketright_bracketnewlineeoferror"

var _Kind_index = [...]uint16{0, 7, 17, 32, 46, 59, 76, 81, 86, 92, 98, 107, 113, 120, 126, 133, 140, 147, 156, 164, 169, 176, 183, 192, 197, 207, 216, 223, 230, 238, 245, 249, 254, 258, 263, 268, 279, 283, 293, 297, 307, 314, 327, 332, 338, 342, 352, 363, 372, 377, 382, 392, 403, 413, 424, 436, 447, 457, 472, 481, 492, 501, 516, 526, 537, 547, 558, 563, 572, 577, 580, 592, 605, 612, 615, 620}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
