name: Pull Request Discord Notification

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: stegzilla/discord-notify@v5
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "Pull Request ${{ github.event.action }}: #${{ github.event.pull_request.number }}"
          message: |
            **${{ github.event.pull_request.title }}**

            Branch: `${{ github.event.pull_request.head.ref }}` into `${{ github.event.pull_request.base.ref }}`
          include_image: true
          avatar_url: ${{ github.event.pull_request.user.avatar_url }}
          username: G${{ github.event.pull_request.user.login }}
          colour: ${{ github.event.action == 'synchronize' && '#3447003' || '#5814783' }}